vim.keymap.set("n", "<space>e", "<cmd>source %<CR>")
vim.keymap.set("n", "<space><space>e", "<cmd>.lua<CR>")
vim.keymap.set("v", "<space>e", ":lua<CR>")
vim.keymap.set("n", "<M-j>", "<cmd>cnext<CR>")
vim.keymap.set("n", "<M-k>", "<cmd>cprev<CR>")
